name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: |
        docker build . --tag slr-model:1.${{ github.run_number }} --file Dockerfile --no-cache

    - name: Login to the Container Repository
      # run: docker login -u rredgrave11621 -p ${{ secrets.DOCKER_HUB_TOKEN }}
      uses: docker/login-action@v3
      with:
        username: rredgrave11621
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    - name: Tag and push to the repository
      run: |
        docker tag slr-model:1.${{ github.run_number }} rredgrave11621/slr-model:1.${{ github.run_number }}
        docker push rredgrave11621/slr-model:1.${{ github.run_number }}
