name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --tag research-repo:0.1 --file Dockerfile --no-cache
    - name: Log in to Docker Hub
      run: docker login -u rredgrave11621 -p ${{ secrets.DOCKER_HUB_TOKEN }}
    - name: Tag the Docker image
      run: docker tag research-repo:0.1 rredgrave11621/research-repo:0.1
    - name: Push the Docker image
      run: docker push rredgrave11621/research-repo:0.1
