name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker build . --tag slr-model:0.1 --file Dockerfile --no-cache

    - name: Login to the Container Repository
      run: echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login ghcr.io -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin
      # uses: docker/login-action@v1
      # with:
      #   registry: ghcr.io
      #   username: ${{ secrets.DOCKER_HUB_USER }}
      #   password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    - name: Tag and push to the repository
      run: |
        docker tag slr-model:0.1 rredgrave11621/slr-model:0.1
        docker push rredgrave11621/slr-model:0.1
